version: "3.8"
services:
  db:
    image: postgres:16.0-alpine
#    container_name: hyper-psql
    restart: always
    environment:
      POSTGRES_USER: hyperUser
      POSTGRES_PASSWORD: hyperPass
      POSTGRES_DB: Hyper
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
